# -*- coding: utf-8 -*-
"""example_21_Exception_Handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6pFcuOtwKZNdgerAsvOdqoASKy-BXDz
"""
# Course title: Udemy Course: Introduction to the Python Language
# Instructor: Dr. Diego Mariano
# Example adapted by: Charles Fernandes de Souza
# Date: July 18, 2021

# Exception Handling

# When an error occurs, or exception as we call it, Python will normally stop and generate an error message: 

try:  # The try block lets you test a block of code for errors.
  print(example)
except: # The except block lets you handle the error.
  print("An exception occurred")

# Many Exceptions:
try:
  print(example)
except NameError:
  print("Variable example is not defined")
except:
  print("Something else went wrong")

try:
  print(x)
except:
  print("Something went wrong")
finally: # The finally block lets you execute code, regardless of the result of the try- and except blocks.
  print("The 'try except' is finished")

# Try to open and write to a file that is not writable:
try:
  f = open("examplefile.txt")
  f.write("To be, or not to be, that is the question")
except:
  print("Something went wrong when writing to the file")
finally:
  f.close()
